#Virtual Wall
virtual_wall:
  left:
    position:
      x: 0.0
      y: -0.2 # [m]
      z: 0.0
    stiffness: 10 # N/mm
    damping: 0

  right:
    position:
      x: 0.0
      y: 0.2  # [m]
      z: 0.0
    stiffness: 10 # N/mm
    damping: 0
