#Virtual Wall
virtual_wall:
  left:
    position:
      x: 0.0
      y: -0.15 # [m]
      z: -0.3
    stiffness: 1000 # N/m
    damping: 0

  right:
    position:
      x: 0.0
      y: 0.15  # [m]
      z: -0.3
    stiffness: 1000 # N/m
    damping: 0
